<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>scopeName</key>
        <string>source.hyp</string>

        <key>fileTypes</key>
        <array>
            <string>hyperlynx</string>
            <string>hyp</string>
            <string>bbd</string>
            <string>bud</string>
            <string>ddr</string>
            <string>dcs</string>
        </array>

        <key>name</key>
        <string>Hyperlynx</string>

        <key>patterns</key>
        <array>
            <dict>
                <key>begin</key>
                <string>\*</string>
                <key>end</key>
                <string>$\n?</string>
                <key>name</key>
                <string>comment.line.hyp</string>
            </dict>
            <dict>
                <key>begin</key>
                <string>\\\\</string>
                <key>end</key>
                <string>$\n?</string>
                <key>name</key>
                <string>comment.line.hyp</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\{(.+)=(.+)\}</string>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.function.hyp</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>support.constant.hyp</string>
                    </dict>
                </dict>
                <key>end</key>
                <string>^\}</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\{(.+)\}</string>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.control.hyp</string>
                    </dict>
                </dict>
                <key>end</key>
                <string>^\}</string>
            </dict>
            <dict>
                <key>begin</key>
                <string>\{(.+)=(.+)</string>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.function.hyp</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>support.constant.hyp</string>
                    </dict>
                </dict>
                <key>end</key>
                <string>^\}</string>
            </dict>
            <dict>
                <key>begin</key>
                <string>\{(.+)</string>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.function.hyp</string>
                    </dict>
                </dict>
                <key>end</key>
                <string>^\}</string>
            </dict>
        </array>
    </dict>
</plist>