<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>pjh</string>
	</array>
	<key>name</key>
	<string>Hyperlynx Project File</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\*</string>
			<key>comment</key>
			<string>Comment</string>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.pjh</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\\\\</string>
			<key>comment</key>
			<string>Comment</string>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.pjh</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Keywords</string>
			<key>match</key>
			<string>\[(.+)\]</string>
			<key>name</key>
			<string>keyword.control.pjh</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.pjh</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>source.pjh</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Settings</string>
			<key>match</key>
			<string>^(.+)=(.+)?</string>
			<key>name</key>
			<string>source.pjh</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.pjh</string>
</dict>
</plist>
