<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>hyperlynx</string>
		<string>hyp</string>
		<string>bbd</string>
		<string>bud</string>
		<string>ddr</string>
		<string>eds</string>
		<string>dcs</string>
		<string>ref</string>
	</array>
	<key>name</key>
	<string>Hyperlynx</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\*</string>
			<key>comment</key>
			<string>Comment</string>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.hyp</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\\\\</string>
			<key>comment</key>
			<string>Comment</string>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.hyp</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\{([^\}=]+)((=)([^\}]+))?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.hyp</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.hyp</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Sections</string>
			<key>contentName</key>
			<string>source.hyp</string>
			<key>end</key>
			<string>(^\}\n)|(\}$\n?)</string>
			<key>name</key>
			<string>source.hyp</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.hyp</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Line Type</string>
					<key>match</key>
					<string>\((\S+)</string>
					<key>name</key>
					<string>source.hyp</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.hyp</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.language.hyp</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Content</string>
					<key>match</key>
					<string>(\S+)(=)([^ \)]+)?</string>
					<key>name</key>
					<string>source.hyp</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.hyp</string>
</dict>
</plist>
