<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>scopeName</key>
        <string>source.telesis</string>

        <key>fileTypes</key>
        <array>
            <string>tel</string>
            <string>telesis</string>
        </array>

        <key>name</key>
        <string>Telesis</string>

        <key>patterns</key>
        <array>
            <dict>
                <key>begin</key>
                <string>\(</string>
                <key>end</key>
                <string>\)</string>
                <key>name</key>
                <string>comment.line.telesis</string>
            </dict>
            <dict>
                <key>begin</key>
                <string>\$</string>
                <key>end</key>
                <string>$\n?</string>
                <key>name</key>
                <string>keyword.control.telesis</string>
            </dict>
            <dict>
                <key>begin</key>
                <string>.*!</string>
                <key>end</key>
                <string>;</string>
                <key>name</key>
                <string>entity.name.function.telesis</string>
            </dict>
            <dict>
                <key>match</key>
                <string>.*;</string>
                <key>name</key>
                <string>support.constant.telesis</string>
            </dict>
        </array>
    </dict>
</plist>